---
language: python
cache:
  - pip
python:
  - '3.6'
services:
  - redis-server
  - rabbitmq
env:
  global:
  - DATABASE_URL="sqlite:///:memory:"
  - DEBUG=False
before_install:
  - pip install flake8
  - flake8
install:
  - pip install -r requirements.txt
script:
  - "./manage.py migrate"
